name: Event Types
 
on:
  push:
    branches:
      - main
      - "feature_*"
    # branches-ignore:
    #   - "feature_*"
    paths:
       - "src/**"
       - "dependencies.txt"

  pull_request:
     branches:
        - main

  issues:
      types: [opened]

  schedule:
     - cron: "48 15 * * *"  

#
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup Python
        run: echo "hello world"
 
